name: "urban"
class_name: "UrbanWorld"

params:
  drone_model: "CF2X"
  num_drones: 1
  physics: "PYB"
  pyb_freq: 240
  ctrl_freq: 48
  gui: true
  
  # Parametry UrbanWorld
  city_length: 1000.0
  city_width: 300.0
  block_size: 30.0    # Budynki 30x30m
  street_width: 10.0  # Wąskie ulice (kaniony) - trudne dla GPS/Slam (w teorii)
  min_height: 15.0
  max_height: 60.0
  skyscraper_prob: 0.15 # Co ok. 7 budynek to ogromny wieżowiec

initial_xyzs:
  - [0.0, 0.0, 0.5] # Start na ulicy

target_position: [1000.0, 0.0, 50.0] # Cel na końcu miasta, na wysokości dachów
