defaults:
  - _self_
  - environment: empty
  - algorithm: trajectory

num_drones: 5

simulation:
  duration_sec: 12
  gui: true
  pyb_freq: 240
  ctrl_freq: 48
  drone_model: "CF2X"
  physics: "PYB"

seed: 42
experiment_name: "test_run"
debug: true
logging:
  enabled: true
  log_freq: 1.0

visualization:
  camera_follow: true
  tracked_drone_id: 0
  camera_distance: 3.0
  camera_yaw: -90.0
  camera_pitch: -30.0

hydra:
  run:
    dir: results/${now:%Y-%m-%d}/${now:%H-%M-%S}_${environment.name}
  
  job_logging:
    version: 1
    root:
      level: INFO
